update bag2folder and folder2bag
snail-radar/dataset_tools pull request #2
Opened 2024-04-28 06:46 UTC by wbl1997

update bag2folder and folder2bag

2024-04-29 06:57 UTC, snail-radar requested changes
写得挺好的，注意添加一下frame id, hardcode即可。另见加注。

2024-04-29 06:57 UTC, snail-radar commented on python/bag_to_folder.py
> +# refer to [coloradar tools](https://github.com/JzHuai0108/coloradar_tools/blob/master/python/bag_to_dataset_fmt.py)
delete

2024-04-29 06:57 UTC, snail-radar commented on python/bag_to_folder.py
> +        elif msg_type == PointCloud2:
also save the times of pointclouds to a file times.txt

2024-04-29 06:57 UTC, snail-radar commented on python/bag_to_folder.py
> +                        f.write(f'{msg.header.stamp.secs}.{msg.header.stamp.nsecs:09d} '
把covariance 对角线的三个数也放上？

2024-04-29 06:57 UTC, snail-radar commented on python/folder_to_bag.py
> +                        msg.pose.pose.position.x = float(parts[1])
写一下固定的header.frame_id和child_frame_id?

2024-04-29 06:57 UTC, snail-radar commented on python/bag_to_folder.py
然后加上一个zip命令，把这个folder直接打成一个zip文件。

2024-04-29 06:57 UTC, snail-radar commented on python/folder_to_bag.py
> +                    msg.header.stamp = rospy.Time(int(parts[0].split('.')[0]), int(parts[0].split('.')[1]))
填一下msg.header.frame_id?

2024-04-29 06:57 UTC, snail-radar commented on python/folder_to_bag.py
> +    header.frame_id = "frame"  # Set the appropriate frame id
当做一个参数传进来，对不同的message设定一下frame id.

2024-04-29 06:57 UTC, snail-radar commented on python/bag_to_folder.py
> +        '/zed2i/zed_node/imu/data': ('zed2i/imu.txt', Imu),
注意一下某些bag里面/zed2/zed_node, 参考radar_data_preprocess 判断zed型号的方式，自适应一下？

2024-04-29 06:57 UTC, snail-radar commented on python/folder_to_bag.py
> +        topic_fields.append(PointField(field, 4*i, PointField.FLOAT32, 1))
这个有点问题，对于hesai pandar,     fields = [PointField('x', 0, PointField.FLOAT32, 1),
            PointField('y', 4, PointField.FLOAT32, 1),
            PointField('z', 8, PointField.FLOAT32, 1),
            PointField('intensity', 16, PointField.FLOAT32, 1),
            PointField('timestamp', 20, PointField.FLOAT64, 1),
            PointField('ring', 28, PointField.UINT16, 1)]

2024-05-14 12:50 UTC, wbl1997 commented on python/bag_to_folder.py
> +        '/zed2i/zed_node/imu/data': ('zed2i/imu.txt', Imu),
我现在bag2folder的时候全部转为/zed2i了。

2024-05-23 03:24 UTC, JzHuai0108 requested changes
1. 那些timestamps.pcd是干啥的？把所有的时间文件都统一命名为times.txt?
2. hesai pandar timestamp数据类型应该是double， 不是float32. 你得仔细检查一下呀：对着保存出来的bag, 每个topic 播放，rviz看，然后每个topic fields对应一下。

2024-06-03 10:17 UTC, merged